##################################################
## ログファイルのプロパティ
##################################################
# ログファイルのディレクトリパス
log_path: /home/pypeach/pypeach_django/log
# ログファイル名
log_file: pypeach_django.log

##################################################
## DB接続のプロパティ
##################################################
database_user: pypeach_django
database_password: pypeach_django
database_host: localhost
database_name: pypeach_django
database_port: 3306
test_database_name: test_pypeach_django
