##################################################
## ログファイルのプロパティ
##################################################
# ログファイルのディレクトリパス
log_path: /home/mocjax/log/
# ログファイル
log_file: virgo_batch.log
# ログファイルの保管数
log_file_backup_count: 30
