##################################################
## ログファイルのプロパティ
##################################################
# ログファイルのディレクトリパス
log_path: C:\work\30.mocjax\log\
# ログファイル
log_file: virgo_batch.log
# ログファイルの保管数
log_file_backup_count: 30
