##################################################
## ログファイルのプロパティ
##################################################
# ログファイルのディレクトリパス
log_path: /home/pypeach/pypeach_django/log
# ログファイル名
log_file: pypeach_django.log
# ログレベル(app)
app_log_level: INFO
# ログレベル(sql)
sql_log_level: INFO

##################################################
## DB接続のプロパティ
##################################################
database_user: pypeach
database_password: pypeach
database_host: localhost
database_name: pypeach
database_port: 3306
test_database_name: test_pypeach

##################################################
## Scrapyのプロパティ
##################################################
url_request_retry_max_count: 3
url_request_read_timeout: 10
